# Generated by Django 5.1.6 on 2025-03-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_investigation_notes_study_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigation',
            name='work_package',
            field=models.CharField(blank=True, choices=[('wpc1', 'WPC1'), ('wpc2', 'WPC2'), ('wpc3', 'WPC3'), ('wpc4', 'WPC4'), ('wpc5', 'WPC5'), ('wpc6', 'WPC6'), ('wpc7', 'WPC7'), ('s1', 'S1'), ('s2', 'S2'), ('s3', 'S3'), ('s4', 'S4'), ('s5', 'S5'), ('s6', 'S6')], help_text='Select the primary work package for this investigation', max_length=10, null=True),
        ),
    ]
