# Generated by Django 5.1.6 on 2025-03-28 10:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_investigation_work_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='study_label',
        ),
        migrations.AddField(
            model_name='study',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(code='invalid_label', message='Slug label must contain only alphanumeric characters, underscores, and hyphens (no spaces or special characters)', regex='^[a-zA-Z0-9_-]+$')]),
        ),
    ]
