# Generated by Django 5.1.6 on 2025-03-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_study_experiment_factor_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigation',
            name='pi_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investigation',
            name='pi_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='pi_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='pi_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
