# Generated by Django 5.1.6 on 2025-03-29 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_investigation_pi_email_investigation_pi_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investigation',
            old_name='pi_email',
            new_name='principal_investigator_email',
        ),
        migrations.RenameField(
            model_name='investigation',
            old_name='pi_name',
            new_name='principal_investigator_name',
        ),
        migrations.RenameField(
            model_name='study',
            old_name='pi_email',
            new_name='principal_investigator_email',
        ),
        migrations.RenameField(
            model_name='study',
            old_name='pi_name',
            new_name='principal_investigator_name',
        ),
    ]
