# Generated by Django 5.1.6 on 2025-04-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "api",
            "0007_rename_pi_email_investigation_principal_investigator_email_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="investigationinstitution",
            options={
                "verbose_name": "Institution",
                "verbose_name_plural": "Institutions",
            },
        ),
        migrations.AlterField(
            model_name="investigation",
            name="participating_institutions",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="research_projects",
                through="api.InvestigationInstitution",
                to="api.institution",
            ),
        ),
    ]
