# Generated by Django 5.1.6 on 2025-04-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_investigationinstitution_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investigation",
            name="participating_institutions",
            field=models.ManyToManyField(
                related_name="research_projects",
                through="api.InvestigationInstitution",
                to="api.institution",
            ),
        ),
    ]
