# Generated by Django 5.2 on 2025-08-19 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_investigation_participating_institutions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="investigation",
            name="principal_investigator",
            field=models.ForeignKey(
                blank=True,
                help_text="Principal investigator for this investigation",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="principal_investigations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="investigation",
            name="work_package",
            field=models.CharField(
                blank=True,
                choices=[
                    ("WPC1", "WPC1"),
                    ("WPC2", "WPC2"),
                    ("WPC3", "WPC3"),
                    ("WPC4", "WPC4"),
                    ("WPC5", "WPC5"),
                    ("WPC6", "WPC6"),
                    ("WPC7", "WPC7"),
                    ("WPT", "WPT"),
                    ("WPD", "WPD"),
                    ("S1", "S1"),
                    ("S2", "S2"),
                    ("S3", "S3"),
                    ("S4", "S4"),
                    ("S5", "S5"),
                    ("S6", "S6"),
                ],
                help_text="Select the primary work package for this investigation",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userrole",
            name="role",
            field=models.CharField(
                choices=[
                    ("guest", "Guest"),
                    ("internal", "Internal"),
                    ("authorized", "Authorized"),
                    ("contributor", "Contributor"),
                    ("owner", "Owner"),
                    ("admin", "Dataset Administrator"),
                ],
                max_length=20,
            ),
        ),
    ]
