# Generated by Django 5.2 on 2025-08-19 10:42

import django.contrib.auth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_study_dataset_administrator"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("auth.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name="investigation",
            name="principal_investigator",
            field=models.ForeignKey(
                blank=True,
                help_text="Principal investigator for this investigation",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="principal_investigations",
                to="api.customuser",
            ),
        ),
        migrations.AlterField(
            model_name="study",
            name="dataset_administrator",
            field=models.ForeignKey(
                blank=True,
                help_text="Dataset administrator for this study",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dataset_administrations",
                to="api.customuser",
            ),
        ),
        migrations.AlterField(
            model_name="userrole",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roles",
                to="api.customuser",
            ),
        ),
    ]
