# Generated by Django 5.2 on 2025-08-19 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_customuser_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assay",
            name="study",
        ),
        migrations.DeleteModel(
            name="Sample",
        ),
        migrations.DeleteModel(
            name="Assay",
        ),
    ]
