# Generated by Django 5.2 on 2025-08-19 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_remove_assay_study_delete_sample_delete_assay"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="investigation",
            name="principal_investigator_email",
        ),
        migrations.RemoveField(
            model_name="investigation",
            name="principal_investigator_name",
        ),
        migrations.RemoveField(
            model_name="study",
            name="principal_investigator_email",
        ),
        migrations.RemoveField(
            model_name="study",
            name="principal_investigator_name",
        ),
    ]
