# Generated by Django 5.1.6 on 2025-02-24 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isa_api', '0003_institution'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestigationInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('join_date', models.DateField()),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isa_api.institution')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isa_api.investigation')),
            ],
            options={
                'unique_together': {('project', 'institution')},
            },
        ),
        migrations.AddField(
            model_name='investigation',
            name='participating_institutions',
            field=models.ManyToManyField(related_name='research_projects', through='isa_api.InvestigationInstitution', to='isa_api.institution'),
        ),
    ]
