# Generated by Django 5.1.6 on 2025-02-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isa_api', '0005_alter_investigation_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigation',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investigation',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
