# Generated by Django 5.1.6 on 2025-02-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isa_api', '0006_alter_investigation_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assay',
            name='name',
            field=models.TextField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
