# Generated by Django 5.1.6 on 2025-02-24 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isa_api', '0007_assay_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assay',
            old_name='name',
            new_name='title',
        ),
    ]
