# Generated by Django 5.1.6 on 2025-02-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isa_api', '0008_rename_name_assay_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession_code', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
