# Generated by Django 5.1.6 on 2025-02-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isa_api', '0010_remove_assay_technology_type_sample_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='sample_type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assay',
            name='measurement_type',
            field=models.CharField(choices=[('genomics', 'Genomics'), ('transcriptomics', 'Transcriptomics'), ('proteomics', 'Proteomics'), ('metabolomics', 'Metabolomics'), ('phenotyping', 'Phenotyping'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='assay',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
