# Generated by Django 5.1.6 on 2025-02-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isa_api', '0011_sample_sample_type_alter_assay_measurement_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='security_level',
            field=models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('restricted', 'Restricted'), ('confidential', 'Confidential')], default='confidential', max_length=20),
        ),
    ]
