# Generated by Django 5.1.6 on 2025-02-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isa_api', '0012_sample_security_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
