# Generated by Django 5.1.6 on 2025-02-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isa_api', '0016_alter_investigationpermission_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='end_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='start_date',
            field=models.DateField(blank=True),
        ),
    ]
