# Generated by Django 5.1.6 on 2025-02-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isa_api', '0017_alter_study_end_date_alter_study_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
