# Generated by Django 5.1.6 on 2025-02-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isa_api', '0019_remove_institution_email_remove_institution_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='address_addition',
            field=models.TextField(blank=True, null=True),
        ),
    ]
