# Generated by Django 5.1.6 on 2025-02-26 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('isa_api', '0020_institution_address_addition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studypermission',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='studypermission',
            name='study',
        ),
        migrations.RemoveField(
            model_name='studypermission',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='assay',
            options={'ordering': ['id'], 'permissions': [('manage_permissions', 'Can manage permissions')]},
        ),
        migrations.AlterModelOptions(
            name='investigation',
            options={'ordering': ['id'], 'permissions': [('manage_permissions', 'Can manage permissions')]},
        ),
        migrations.AlterModelOptions(
            name='sample',
            options={'ordering': ['id'], 'permissions': [('manage_permissions', 'Can manage permissions')]},
        ),
        migrations.AlterModelOptions(
            name='study',
            options={'ordering': ['id'], 'permissions': [('manage_permissions', 'Can manage permissions')]},
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('guest', 'Guest'), ('internal', 'Internal'), ('authorized', 'Authorized'), ('contributor', 'Contributor'), ('owner', 'Owner'), ('admin', 'Admin')], max_length=20)),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='InvestigationPermission',
        ),
        migrations.DeleteModel(
            name='StudyPermission',
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['content_type', 'object_id'], name='isa_api_use_content_e3e726_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('user', 'content_type', 'object_id')},
        ),
    ]
