# Generated by Django 5.1.6 on 2025-02-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isa_api', '0021_alter_studypermission_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigation',
            name='public_release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investigation',
            name='submission_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
