# Generated by Django 5.1.6 on 2025-02-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isa_api', '0022_alter_investigation_public_release_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='study_design',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='submission_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
