# Generated by Django 5.1.6 on 2025-02-27 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isa_api', '0023_alter_study_description_alter_study_study_design_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investigation',
            options={'permissions': [('manage_permissions_investigation', 'Can manage permissions for investigation')]},
        ),
        migrations.AlterModelOptions(
            name='study',
            options={'permissions': [('manage_permissions_study', 'Can manage permissions for study')]},
        ),
    ]
