# Generated by Django 5.1.6 on 2025-02-27 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isa_api', '0024_alter_investigation_options_alter_study_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investigation',
            options={'ordering': ['id'], 'permissions': [('manage_permissions_investigation', 'Can manage permissions for investigation')]},
        ),
        migrations.AlterModelOptions(
            name='study',
            options={'ordering': ['id'], 'permissions': [('manage_permissions_study', 'Can manage permissions for study')]},
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='title',
            new_name='name',
        ),
    ]
