# Generated by Django 5.1.6 on 2025-02-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isa_api', '0025_alter_investigation_options_alter_study_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
