# Generated by Django 5.1.6 on 2025-02-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isa_api', '0027_alter_sample_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
