# Generated by Django 5.1.6 on 2025-02-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isa_api', '0028_alter_sample_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='public_release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
